module Test.UT.Modules.FontSubset (suiteName, testCases) where

import Control.Exception (bracket_)
import Modules.Config
import Modules.FontSubset
import Modules.Utils.TempDir (withTempDir)
import System.Directory
  ( createDirectoryIfMissing
  , doesFileExist
  , getCurrentDirectory
  , getTemporaryDirectory
  , setCurrentDirectory
  )
import System.Environment (lookupEnv, setEnv, unsetEnv)
import System.FilePath ((</>))
import System.Process (callProcess)
import Test.Framework.Asserts
import Test.Framework.TestSuite

suiteName :: String
suiteName = "FontSubset"

testCases :: [TestCase]
testCases =
  [ testMkFontSetDeduplicatesChars
  , testMkPyftsubsetArgsStable
  , testGenFontSubsetWritesFontSetAndCallsPyftsubset
  ]

testMkFontSetDeduplicatesChars :: TestCase
testMkFontSetDeduplicatesChars =
  mkTestCase "mkFontSet deduplicates characters from index and post htmls" $ do
    let fontSet = mkFontSet "aab" ["bcc", "dda"]
    assertTrue "font set should contain unique char a" ('a' `elem` fontSet)
    assertTrue "font set should contain unique char b" ('b' `elem` fontSet)
    assertTrue "font set should contain unique char c" ('c' `elem` fontSet)
    assertTrue "font set should contain unique char d" ('d' `elem` fontSet)
    assertEq "font set should contain exactly 4 unique chars" 4 (length fontSet)

testMkPyftsubsetArgsStable :: TestCase
testMkPyftsubsetArgsStable =
  mkTestCase "mkPyftsubsetArgs returns deterministic production args" $ do
    assertEq "pyftsubset args should match configured production constants"
      [ originFontFilePath
      , "--text-file=" ++ fontSetPath
      , "--flavor=woff2"
      , "--output-file=" ++ subsetFontFilePath
      ]
      mkPyftsubsetArgs

testGenFontSubsetWritesFontSetAndCallsPyftsubset :: TestCase
testGenFontSubsetWritesFontSetAndCallsPyftsubset =
  mkTestCase "genFontSubset writes fontset.txt and invokes pyftsubset with output path" $ do
    tempRoot <- getTemporaryDirectory
    let workRoot = tempRoot </> "xilong-site-ut-fontsubset"
    withTempDir workRoot $ do
      oldCwd <- getCurrentDirectory
      let binDir = workRoot </> "bin"
          tracePath = workRoot </> "pyftsubset.trace"
      createDirectoryIfMissing True binDir
      writeFakePyftsubset (binDir </> "pyftsubset")
      withWorkDir workRoot $ do
        setupFixtureTree
        withEnv "PYFTSUBSET_TRACE" tracePath $
          withPrependedPath binDir genFontSubset
      setCurrentDirectory oldCwd
      fontSetExists <- doesFileExist (workRoot </> fontSetPath)
      subsetExists <- doesFileExist (workRoot </> subsetFontFilePath)
      traceExists <- doesFileExist tracePath
      assertTrue "fontset.txt should be generated" fontSetExists
      assertTrue "subset font output should be generated by fake pyftsubset" subsetExists
      assertTrue "fake pyftsubset should leave invocation trace" traceExists
      trace <- readFile tracePath
      assertContains "trace should contain flavor option" "--flavor=woff2" trace
      assertContains "trace should contain output-file option"
        ("--output-file=" ++ subsetFontFilePath)
        trace

setupFixtureTree :: IO ()
setupFixtureTree = do
  createDirectoryIfMissing True tempPath
  createDirectoryIfMissing True postPath
  createDirectoryIfMissing True fontPath
  writeFile indexPath "<html><body>INDEX</body></html>"
  writeFile (postPath </> "a.html") "<main>POST A</main>"
  writeFile (postPath </> "b.html") "<main>POST B</main>"
  writeFile originFontFilePath "fake-otf"

writeFakePyftsubset :: FilePath -> IO ()
writeFakePyftsubset scriptPath = do
  writeFile scriptPath $
    unlines
      [ "#!/bin/sh"
      , "printf '%s\\n' \"$@\" > \"$PYFTSUBSET_TRACE\""
      , "for arg in \"$@\"; do"
      , "  case \"$arg\" in"
      , "    --output-file=*) out=\"${arg#--output-file=}\" ;;"
      , "  esac"
      , "done"
      , "[ -n \"$out\" ] && : > \"$out\""
      ]
  callProcess "chmod" ["+x", scriptPath]

withWorkDir :: FilePath -> IO a -> IO a
withWorkDir dir action = do
  old <- getCurrentDirectory
  bracket_ (setCurrentDirectory dir) (setCurrentDirectory old) action

withPrependedPath :: FilePath -> IO a -> IO a
withPrependedPath path action = do
  old <- lookupEnv "PATH"
  let newPath = case old of
        Just existing -> path ++ ":" ++ existing
        Nothing -> path
  bracket_ (setEnv "PATH" newPath) (restore old) action
  where
    restore (Just value) = setEnv "PATH" value
    restore Nothing = unsetEnv "PATH"

withEnv :: String -> String -> IO a -> IO a
withEnv key value action = do
  old <- lookupEnv key
  bracket_ (setEnv key value) (restore old) action
  where
    restore (Just oldValue) = setEnv key oldValue
    restore Nothing = unsetEnv key
